sudo: false
language: node_js
before_script:
  - npm install react@15.4.1
  - npm install react-dom@15.4.1
node_js:
  - '4.4.4'
  - '5'
  - '6'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
